# Generated by Django 6.0.3 on 2026-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes_per_day",
                    models.IntegerField(default=30, help_text="Минут в день"),
                ),
                (
                    "words_per_day",
                    models.IntegerField(default=10, help_text="Слов в день"),
                ),
                (
                    "exercises_per_day",
                    models.IntegerField(default=5, help_text="Упражнений в день"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("minutes_spent", models.IntegerField(default=0)),
                ("words_learned", models.IntegerField(default=0)),
                ("exercises_completed", models.IntegerField(default=0)),
                ("points_earned", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnownWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mastered",
                    models.BooleanField(default=False, help_text="Полностью освоено"),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("last_reviewed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="Процент правильных ответов"
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(default=0, help_text="Время в секундах"),
                ),
                ("attempts", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("lessons_completed", models.IntegerField(default=0)),
                ("exercises_solved", models.IntegerField(default=0)),
                ("words_learned", models.IntegerField(default=0)),
                ("streak_days", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
