# Generated by Django 6.0.3 on 2026-04-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailygoal",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_goal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="courses.exercise",
            ),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="knownword",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="known_words",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knownword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.vocabularyword"
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="current_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.level",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="english_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystats",
            unique_together={("user", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="exerciseresult",
            unique_together={("user", "exercise")},
        ),
        migrations.AlterUniqueTogether(
            name="knownword",
            unique_together={("user", "word")},
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("user", "lesson")},
        ),
    ]
