# Generated by Django 6.0.3 on 2026-04-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("learning", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="current_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.level",
            ),
        ),
    ]
