# Generated by Django 6.0.3 on 2026-04-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrammarRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("rule", models.TextField(help_text="Правило с примерами")),
                ("examples", models.TextField(help_text="Примеры использования")),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("A1", "Beginner (A1)"),
                            ("A2", "Elementary (A2)"),
                            ("B1", "Intermediate (B1)"),
                            ("B2", "Upper Intermediate (B2)"),
                            ("C1", "Advanced (C1)"),
                            ("C2", "Proficient (C2)"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("vocabulary", "Словарный запас"),
                            ("grammar", "Грамматика"),
                            ("listening", "Аудирование"),
                            ("reading", "Чтение"),
                            ("speaking", "Разговорная практика"),
                            ("writing", "Письмо"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Основной контент урока")),
                ("order", models.IntegerField(default=0)),
                ("duration_minutes", models.IntegerField(default=0)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "grammar_rules",
                    models.ManyToManyField(
                        blank=True, related_name="lessons", to="courses.grammarrule"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.level",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "order"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Выбор правильного ответа"),
                            ("fill_blank", "Заполнить пропуск"),
                            ("matching", "Сопоставление"),
                            ("translation", "Перевод"),
                            ("listening", "Аудирование"),
                            ("writing", "Написание"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                ("correct_answer", models.TextField()),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Для multiple_choice: список вариантов",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Объяснение правильного ответа"
                    ),
                ),
                ("points", models.IntegerField(default=10)),
                ("order", models.IntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="grammarrule",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grammar_rules",
                to="courses.level",
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="courses.level",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="courses.topic",
            ),
        ),
        migrations.AddField(
            model_name="grammarrule",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="grammar_rules", to="courses.topic"
            ),
        ),
        migrations.CreateModel(
            name="VocabularyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("translation", models.CharField(max_length=200)),
                ("transcription", models.CharField(blank=True, max_length=100)),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("noun", "Существительное"),
                            ("verb", "Глагол"),
                            ("adjective", "Прилагательное"),
                            ("adverb", "Наречие"),
                            ("preposition", "Предлог"),
                            ("conjunction", "Союз"),
                        ],
                        max_length=50,
                    ),
                ),
                ("definition", models.TextField(blank=True)),
                (
                    "example",
                    models.TextField(blank=True, help_text="Пример использования"),
                ),
                ("example_translation", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("audio_url", models.URLField(blank=True)),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Легкий"), (2, "Средний"), (3, "Сложный")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary",
                        to="courses.level",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="vocabulary", to="courses.topic"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vocabulary words",
                "ordering": ["word"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="vocabulary_words",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="courses.vocabularyword"
            ),
        ),
    ]
